# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_theming_backend_theme_switch:
    pattern: /{id}/switch
    defaults: { _controller: sylius_theming.controller.backend.theme:switchAction }

sylius_theming_backend_theme_toggle:
    pattern: /{id}/toggle
    defaults: { _controller: sylius_theming.controller.backend.theme:toggleAction }

sylius_theming_backend_theme_install:
    pattern: /{id}/install
    defaults: { _controller: sylius_theming.controller.backend.theme:installAction }

sylius_theming_backend_theme_uninstall:
    pattern: /{id}/uninstall
    defaults: { _controller: sylius_theming.controller.backend.theme:uninstallAction }

sylius_theming_backend_theme_list:
    pattern: /list
    defaults: { _controller: sylius_theming.controller.backend.theme:listAction }

sylius_theming_backend_theme_show:
    pattern: /{id}
    defaults: { _controller: sylius_theming.controller.backend.theme:showAction }
