# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_theming_theme_list:
    pattern: /
    defaults: { _controller: sylius_theming.controller.frontend.theme:listAction }

sylius_theming_theme_switch:
    pattern: /{id}/switch
    defaults: { _controller: sylius_theming.controller.frontend.theme:switchAction }
